config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "static_pages#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get "/login", to: "sessions#new", as: :login
  delete "/logout", to: "sessions#destroy", as: :logout
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'contact', to: 'static_pages#contact'

  resources :users, only: %i[index show edit update]
  resources :lists do
    resources :books, except: %i[index]
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_books, dependent: :destroy
  has_many :books, through: :list_books

  validates :name, presence: true
  validates :is_public, inclusion: { in: [true, false] }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_current_user_list, only: [:edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :show]

  def index
    @lists = List.where(is_public: true).includes(:user, :books).order(created_at: :desc)
  end

  def new
    @list = List.new
  end

  def create
    @list = current_user.lists.build(list_params)
    if @list.save
      redirect_to new_list_book_path(list_id: @list.id), success: 'リストを作成しました'
    else
      flash.now[:warning] = 'リスト作成に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find_by(id: params[:id])
    if @list.nil?
      redirect_to lists_path, warning: "リストがありません"
    else
      @list_books = @list.list_books.includes(:book)
    end
  end

  def edit; end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list), success: 'リストを更新しました'
    else
      flash.now[:warning] = 'リスト更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @list.destroy
      redirect_to user_path(current_user), success: 'リストを削除しました'
    else
      flash.now[:warning] = 'リスト削除に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :is_public)
  end

  def set_current_user_list
    @list = current_user.lists.find_by(id: params[:id])
    unless @list
      redirect_to lists_path, error: "リストが見つかりません"
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
  def share_link(list)

    text = current_user&.id == list.user_id ? "来年読みたいリスト" : "おすすめのリスト"
    text += "【#{list.name}】をチェック📕👀"

    params = {
      text: text,
      url: request.original_url,
      hashtags: "来読"
    }

    url = "https://x.com/intent/tweet"
    "#{url}?#{params.to_query}"
  end
end

app/views/lists/_form.html.erb
<div class="form-control">
  <%= form.label :name, "リスト名", class: "label" %>
  <span class="text-red-600 align-top">*</span>
  <%= form.text_field :name, required: true, class: "input input-bordered w-full" %>
</div>

<div class="form-control">
  <% if current_user.is_public %>
    <%= form.label :is_public, "公開する", class: "label" %>
    <%= form.check_box :is_public, class: "checkbox checkbox-primary" %>
  <% else %>
    <%= form.label :is_public, "公開する", class: "label text-gray-400" %>
    <%= form.check_box :is_public, class: "checkbox checkbox-primary", disabled: true %>
    <p class="text-gray-500 text-sm">非公開ユーザーのリストは公開できません</p>
  <% end %>
</div>

app/views/lists/_link_button.html.erb
<div class="flex justify-center gap-2">
  <%= link_to '書籍登録画面', new_list_book_path(@list.id), class: 'btn btn-primary' %>
  <%= link_to 'Xシェア', share_link(@list), class: 'btn btn-primary', target: "_blank" %>
</div>
<%= link_to 'リスト一覧に戻る', lists_path, class: 'link' %>

app/views/lists/_list.html.erb
<li class="card bg-base-100 w-[95%] shadow-xl mx-auto rounded-none lg:w-full">
  <% if list.books.count > 0 %>
    <figure class="bg-white py-3">
      <%= image_tag(list.books.first.cover_image_url, alt: list.books.first.title) %>
    </figure>
  <% else %>
    <p class="bg-white py-3 text-center w-[200px] h-[224px] flex justify-center items-center m-auto">書籍登録がありません</p>
  <% end %>
  <div class="card-body bg-orange-100">
    <div>
      <h2 class="text-lg font-semibold"><%= list.name %></h2>
      <p>
        作成者: <%= link_to list.user.name, user_path(list.user), class: "link link-primary" %><br />
        エンジニア開始日: <%= list.user.engineer_start_date&.strftime("%Y年%m月%d日") %><br />
        書籍登録数： <%= list.books.count %>冊
      </p>
      <div class="card-actions justify-end">
        <%= link_to '詳細', list_path(list), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</li>

app/views/lists/edit.html.erb
<article class="flex flex-col items-center justify-center gap-8 w-full">
  <h1 class="zen-maru-gothic-bold text-4xl text-center mb-4"><%= title "リスト編集" %></h1>
  <%= form_with(model: @list, local: true, class: "space-y-4") do |form| %>
    <%= render 'form', form: form %>
  <div class="flex gap-5 justify-center items-center">
    <%= link_to "削除", list_path(@list), data: { turbo_method: :delete }, class: "btn btn-error" %>
    <%= form.submit "更新", class: "btn btn-primary" %>
  </div>
  <% end %>
  <%= link_to "戻る", lists_path, class: "link" %>
</article>

app/views/lists/index.html.erb
<article class="flex flex-col items-center justify-center gap-8 w-full">
  <h1 class="zen-maru-gothic-bold text-4xl text-center mb-4"><%= title "リスト一覧" %></h1>
  <div class="flex flex-col items-center w-full">
    <ul class="w-full grid grid-cols-1 justify-center items-start gap-4 lg:grid-cols-3">
      <% @lists.each do |list| %>
        <% next unless list.books.present? %>
        <%= render list %>
      <% end %>
    </ul>
  </div>
</article>

app/views/lists/new.html.erb
<article class="flex flex-col items-center justify-center gap-8 w-full">
  <h1 class="zen-maru-gothic-bold text-4xl text-center mb-4"><%= title "リストの新規作成" %></h1>
  <%= form_with(model: @list, local: true, class: "space-y-4") do |form| %>
    <%= render 'form', form: form %>
    <div class="form-control">
      <%= form.submit "作成", class: "btn btn-primary w-full" %>
    </div>
  <% end %>
  <%= link_to "戻る", lists_path, class: "link" %>
</article>

app/views/lists/show.html.erb
<article class="flex flex-col items-center justify-between gap-4 w-full">
  <h1 class="text-4xl text-center mb-4 zen-maru-gothic-bold"><%= title @list.name %></h1>
  <div class="flex justify-center items-center gap-2">
    <h2 class="text-lg font-semibold"><%= @list.user.name %>さんのリスト</h2>
    <% if current_user&.id == @list.user_id %>
      <%= link_to '編集', edit_list_path(@list.id), class: 'link link-primary' %>
    <% end %>
  </div>
  <%= render 'link_button' %>
  <div class="flex justify-center w-full">
    <ul class="w-full grid grid-cols-1 justify-center items-start gap-4 lg:grid-cols-3">
      <% @list_books.each do |list_book| %>
        <li class="card bg-base-100 w-[95%] shadow-xl mx-auto rounded-none">
          <figure class="bg-white py-3">
            <%= image_tag(list_book.book.cover_image_url, alt: list_book.book.title) %>
          </figure>
          <div class="card-body bg-orange-100">
            <div>
              <h2 class="text-lg font-semibold"><%= list_book.book.title %></h2>
              <p>読了日時: <%= list_book.read_completed_at.strftime('%Y年%m月%d日') %></p>
              <p class="line-clamp-2">コメント: <%= list_book.comment %></p>
              <div class="card-actions justify-end">
                <%= link_to '詳細', list_book_path(@list.id, list_book.book_id), class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <% if @list_books.count > 0 %>
    <%= render 'link_button' %>
  <% end %>
</article>