config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "static_pages#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get "/login", to: "sessions#new", as: :login
  delete "/logout", to: "sessions#destroy", as: :logout
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'contact', to: 'static_pages#contact'

  resources :users, only: %i[index show edit update]
  resources :lists do
    resources :books, except: %i[index]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists, dependent: :destroy
  has_one :authentication, dependent: :destroy

  validates :name, presence: true
  scope :publicly_visible, -> { where(is_public: true) }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authorize_user, only: [:edit, :update]
  skip_before_action :require_login, only: [:index, :show]
  rescue_from ActiveRecord::RecordNotFound, with: :user_not_found

  def index
    @users = User.publicly_visible.order(created_at: :desc).includes(:lists)
  end

  def show
    unless @user.is_public
      # ログインユーザーが自分自身の場合は表示、それ以外はリダイレクト
      unless current_user&.id == @user.id
        redirect_to users_path, warning: "表示権限がありません"
      end
    end
  end

  def edit; end

  def update
    # authorize_userメソッドで処理
    if @user.update(user_params)
      # ユーザーが非公開になるとリストも全て非公開にする
      unless @user.is_public
        @user.lists.each do |list|
          list.is_public = false
          list.save!
        end
      end
      redirect_to user_path(params[:id]), success: "ユーザー情報を更新しました"
    else
      flash.now[:warning] = "ユーザー情報の更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def authorize_user
    unless current_user && current_user.id == @user.id
      redirect_to users_path, warning: "他のユーザー情報は編集できません"
    end
  end

  def user_not_found
    redirect_to users_path, warning: "指定されたユーザーは存在しません"
  end

  def user_params
    params.require(:user).permit(:name, :engineer_start_date, :profile_content, :is_public)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<script type="module" src="https://unpkg.com/cally"></script>
<article class="flex flex-col items-center justify-center gap-8 w-full">
  <h1 class="zen-maru-gothic-bold text-4xl text-center mb-4">プロフィール編集</h1>

  <div class="w-full max-w-md p-6 border rounded shadow bg-white">
    <%= form_with model: @user do |form| %>
      <div class="mb-4">
        <div class="flex">
          <%= form.label :name, "名前", class: "block text-lg font-semibold mb-1" %>
          <span class="text-red-600 align-top">*</span>
        </div>
        <%= form.text_field :name, class: "input" %>
      </div>

      <div class="mb-4">
        <%= form.label :engineer_start_date, "エンジニア開始日", class: "block text-lg font-semibold mb-1" %>
        <button type="button" popovertarget="cally-popover1" class="input input-border" style="anchor-name:--cally1" id="cally1">
          <%= @user.engineer_start_date %>
        </button>
        <%= form.hidden_field :engineer_start_date, id: "engineer_start_date" %>
        <div popover id="cally-popover1" class="dropdown bg-base-100 rounded-box shadow-lg" style="position-anchor:--cally1">
          <calendar-date class="cally" onChange="document.getElementById('cally1').innerText = this.value;document.getElementById('engineer_start_date').value = this.value;" max="<%= Date.today %>" locale="ja-JP">
            <svg aria-label="Previous" class="fill-current size-4" slot="previous" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M15.75 19.5 8.25 12l7.5-7.5"></path></svg>
            <svg aria-label="Next" class="fill-current size-4" slot="next" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m8.25 4.5 7.5 7.5-7.5 7.5"></path></svg>
            <calendar-month></calendar-month>
          </calendar-date>
        </div>
      </div>

      <div class="mb-4">
        <%= form.label :profile_content, "プロフィール文", class: "block text-lg font-semibold mb-1" %>
        <%= form.text_area :profile_content, class: "textarea w-full h-30" %>
      </div>

      <div class="mb-4">
        <div class="flex gap-4 justify-start items-center">
          <div class="flex gap-1 justify-start items-center">
            <%= form.radio_button :is_public, "true", class: "radio" %>
            <%= form.label :is_public_true, "公開" %>
          </div>
          /
          <div class="flex gap-1 justify-start items-center">
            <%= form.radio_button :is_public, "false", class: "radio" %>
            <%= form.label :is_public_false, "非公開" %>
          </div>
        </div>
      </div>

      <div class="flex justify-center">
        <%= form.submit "更新", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <div class="mt-8 flex justify-center">
    <%= link_to 'プロフィールに戻る', user_path(@user), class: 'btn btn-primary' %>
  </div>
</article>

app/views/users/index.html.erb
<div class="container mx-auto px-4 py-8">
  <h1 class="zen-maru-gothic-bold text-4xl text-center mb-6">ユーザー一覧</h1>

  <div class="flex justify-center mb-12">
    <ul class="grid gap-6 w-full max-w-2xl sm:grid-cols-2 lg:grid-cols-3">
      <% @users.each do |user| %>
        <li class="card bg-base-100 shadow-md border hover:shadow-lg transition-shadow duration-300">
          <div class="card-body p-6">

            <!-- ユーザーごとの基本情報 -->
            <div class="flex items-center gap-4 mb-2 pb-2">
              <div class="w-full">
                <p class="text-lg font-bold mb-1"><%= user.name %></p>
                <% if user.engineer_start_date.present? %>
                  <p class="text-sm text-gray-500">
                    エンジニア歴
                    <!-- エンジニア開始日と今日の日付差分をdistance_of_time_in_wordsで処理。日本語化 -->
                    <%= distance_of_time_in_words(user.engineer_start_date, Date.current, locale: :ja) %>
                  </p>
                <% end %>
              </div>
            </div>

            <!-- リスト数 -->
            <div class="mb-4">
              <span class="badge badge-outline badge-md">
                公開リスト
                <span class="ml-1 font-semibold"><%= user.lists.where(is_public: true).count %></span>
                件
              </span>
            </div>

            <div class="card-actions justify-end mt-auto pt-2">
              <%= link_to '詳細を見る', user_path(user), class: 'btn btn-primary btn-sm' %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<article class="flex flex-col items-center justify-center gap-3 lg:max-w-4xl lg:mx-auto">
  <section class="flex flex-col justify-center w-full border shadow-md bg-white border-gray-500 p-4 rounded-lg lg:py-6 lg:px-8">
    <div>
      <div class="flex flex-col items-center mb-6">
        <%# <div class="avatar mb-4">
          <div class="w-24 rounded-full bg-gray-200 flex items-center justify-center">
            画像実装はこちらに
          </div>
        </div>
        %>
        <h2 class="text-xl font-bold"><%= title @user.name %>さん</h2>
      </div>

      <div class="mb-4">
        <strong class="block text-lg font-semibold mb-1">エンジニア開始日</strong>
        <p class="text-gray-700"><%= @user.engineer_start_date&.strftime('%Y年%m月%d日') || '未設定' %></p>
      </div>

      <div class="mb-4">
        <strong class="block text-lg font-semibold mb-1">プロフィール文</strong>
        <p class="text-gray-700 whitespace-pre-wrap"><%= @user.profile_content || '未設定' %></p>
      </div>

      <div>
        <strong class="block text-lg font-semibold mb-1">公開/非公開</strong>
        <p class="text-gray-700"><%= @user.is_public ? '公開' : '非公開' %></p>
      </div>
    </div>
    <% if current_user&.id == @user.id %>
      <div class="flex justify-center">
        <%= link_to '編集', edit_user_path(@user), class: 'link' %>
      </div>
    <% end %>
  </section>

  <section class="flex flex-col justify-center gap-4 w-full">
    <% if current_user&.id == @user.id %>
      <div class="text-center my-4">
        <%= link_to 'リストを作る', new_list_path, class: "btn" %>
      </div>
    <% end %>
    <% if @user.lists.count > 0 %>
      <ul class="grid grid-cols-1 gap-6 lg:grid-cols-3">
        <% @user.lists.each do |list| %>
          <% if list.is_public || current_user&.id == @user.id %>
            <%= render 'lists/list', list: list %>
          <% end %>
        <% end %>
      </ul>
      <% if current_user&.id == @user.id %>
        <div class="text-center my-4">
          <%= link_to 'リストを作る', new_list_path, class: "btn" %>
        </div>
      <% end %>
    <% end %>
  </div>

  <section class="flex justify-center">
    <%= link_to 'ユーザー一覧へ戻る', users_path, class: 'btn btn-primary mr-2'  %>
    <%= link_to 'TOPへ戻る', root_path, class: 'btn btn-primary' %>
  </section>
</article>