config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "static_pages#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get "/login", to: "sessions#new", as: :login
  delete "/logout", to: "sessions#destroy", as: :logout
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'contact', to: 'static_pages#contact'

  resources :users, only: %i[index show edit update]
  resources :lists do
    resources :books, except: %i[index]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_categories, dependent: :destroy
  has_many :categories, through: :book_categories
  has_many :list_books, dependent: :destroy
  has_many :lists, through: :list_books

  validates :title, presence: true
  validates :url, presence: true, format: { with: URI::regexp(%w[http https]), message: 'URLが不正です' }
  validates :isbn, presence: true, uniqueness: true, format: { with: /\A\d{10}(\d{3})?\z/, message: 'ISBNは10桁または13桁の数字でなければなりません' }
  validates :cover_image_url, presence: true, format: { with: URI::regexp(%w[http https]), message: '表紙画像のURLが不正です' }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :require_login, only: [:show]
  before_action :set_current_user_list, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_current_user_list_book, only: [:edit, :update]

  def new
    search_params = params.permit(:title, :commit, :list_id)
    @result = RakutenBooksApiService.search(search_params[:title]) if search_params[:title].present?

    @books = @list.books
    @categories = Category.all
    @existing_isbns = @books.pluck(:isbn)
  end

  def create
    begin
      book = Book.find_or_create_by!(isbn: books_params[:isbn]) do |b|
        b.title = books_params[:title]
        b.cover_image_url = books_params[:cover_image_url]
        b.url = books_params[:url]
      end

      if book.categories.nil? || book.categories.count < 3
        category_ids = books_params[:categories].map do |category_name|
          Category.find_by_name(category_name)&.id
        end.compact
        book.categories = Category.where(id: category_ids)
      end

      unless @list.books.include?(book)
        @list.list_books.find_or_create_by!(list_id: @list.id, book_id: book.id) do |list_book|
          list_book.read_completed_at = books_params[:read_completed_at]
          list_book.comment = books_params[:comment]
        end
        books_and_list_reload
      end

      respond(book)

      flash.now[:success] = "リストに登録完了しました"
    rescue ActiveRecord::RecordInvalid => e
      Rails.logger.error("Error creating book: #{e.message}")
      flash.now[:warning] = "本の登録に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find_by(id: params[:list_id])
    unless @list
      redirect_to lists_path, warning: "リストが見つかりません"
      return
    end

    @list_book = @list.list_books.find_by(list_id: @list.id, book_id: params[:id])
    unless @list_book
      redirect_to lists_path, warning: "リストに本が見つかりません"
      return
    end

    @book = Book.find_by(id: params[:id])
  end

  def edit
    @book = Book.find_by(id: params[:id])
  end

  def update
    if @list_book.update(list_book_params)
      flash.now[:success] = "本の情報を更新しました"
      redirect_to list_book_path(@list, @list_book.book_id), status: :see_other
    else
      flash.now[:warning] = "本の情報の更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      book = Book.find_by(isbn: params[:id])
      if book
        @list.list_books.find_by(book_id: book.id)&.destroy!
      else
        flash.now[:error] = "本が見つかりません"
      end

      if request.referer&.match(%r{/lists/\d+/books/new})
        books_and_list_reload
        respond(book)
        flash.now[:success] = "本をリストから削除しました"
        return
      end

      redirect_to list_path(@list.id), success: "本をリストから削除しました"
    rescue ActiveRecord::RecordNotFound => e
      Rails.logger.error("Error deleting book: #{e.message}")
      flash.now[:warning] = "本の削除に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def books_params
    params.permit(
    :title, :isbn, :cover_image_url, :url,
    :read_completed_at, :comment, :list_id,
    categories: []
  )
  end

  def list_book_params
    params.require(:list_book).permit(
      :read_completed_at, :comment
    )
  end

  def set_current_user_list
    @list = current_user.lists.find_by(id: params[:list_id])
    unless @list
      redirect_to lists_path, warning: "リストが見つかりません"
    end
  end

  def set_current_user_list_book
    @list_book = @list.list_books.find_by(list_id: @list.id, book_id: params[:id])
    unless @list_book
      redirect_to lists_path, warning: "リストに本が見つかりません"
    end
  end

  def respond(book)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "book_#{book.isbn}",
          partial: 'book',
          locals: {
            book: book.as_json.symbolize_keys,
            list: @list,
            existing_isbns: @existing_isbns
          }
        )
      end
    end
  end

  def books_and_list_reload
    @books = @list.books.reload
    @existing_isbns = @books.pluck(:isbn)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def hasCategory?(isbn)
    book = Book.find_by_isbn(isbn)
    if book&.categories.present?
      categories = book.categories.map(&:name)
      if book.categories.count < 3
        categories << '未設定'
      end
      categories
    else
      ["未設定","未設定","未設定"]
    end
  end
end

app/views/books/_book.html.erb
<section id="book_<%= book[:isbn] %>" class="bg-white p-4 flex flex-col items-center justify-center gap-4 w-full">
  <div class="bg-white p-4 flex flex-col items-center justify-between gap-4 w-full">
    <figure>
      <%= image_tag(book[:cover_image_url], alt: book[:title]) %>
    </figure>
    <h2 class="text-xl font-bold link link-primary"><a href="<%= book[:url] %>" target="_blankc" ><%= book[:title] %></a></h2>
    <% if @existing_isbns&.include?(book[:isbn]) %>
      <%= form_with url: list_book_path(list_id: @list.id, id: book[:isbn]), method: :delete, data: { turbo: true } do |form| %>
        <%= form.submit "リストから削除", class: "btn btn-error" %>
      <% end %>
    <% else %>
      <%= form_with url: list_books_path(list_id: @list.id), data: { turbo: true }, class: "w-full flex flex-col gap-4" do |form| %>
        <section class="w-full">
          <h3 class="text-lg font-semibold">カテゴリ</h3>
          <ul class="flex gap-2 w-full justify-center items-center">
            <% hasCategory = hasCategory?(book[:isbn]) %>
            <% hasCategory.each do |category| %>
              <% if category.blank? || category == '未設定' %>
                <li class="w-full"><%= select_tag 'categories[]',
                                options_for_select(['未設定'] + Category.all.map(&:name), selected: '未設定'),
                                class: "select w-full" %>
                </li>
              <% else %>
                <li class="badge"><%= category %></li>
              <% end %>
            <% end %>
          </ul>
        </section>
        <section class="text-start w-full flex flex-col items-start gap-2">
          <div class="w-full">
            <div class="flex items-center">
              <%= form.label :read_completed_at, "読了日", class: "block text-lg font-semibold mb-1" %>
              <span class="text-red-600 align-top">*</span>
            </div>
            <button type="button" popovertarget="cally-popover<%= book[:isbn] %>" class="input input-border w-full" style="anchor-name:--cally<%= book[:isbn] %>" id="cally-<%= book[:isbn] %>">
              読了日
            </button>
            <%= form.hidden_field :read_completed_at, id: "read_completed_at-#{book[:isbn]}" %>
            <div popover id="cally-popover<%= book[:isbn] %>" class="dropdown bg-base-100 rounded-box shadow-lg" style="position-anchor:--cally<%= book[:isbn] %>">
              <calendar-date class="cally" onChange="document.getElementById('cally-<%= book[:isbn] %>').innerText = this.value;document.getElementById('read_completed_at-<%= book[:isbn] %>').value = this.value;document.getElementById('submit-<%= book[:isbn] %>').disabled = false;" max="<%= Date.today %>" locale="ja-JP">
                <svg aria-label="Previous" class="fill-current size-4" slot="previous" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M15.75 19.5 8.25 12l7.5-7.5"></path></svg>
                <svg aria-label="Next" class="fill-current size-4" slot="next" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m8.25 4.5 7.5 7.5-7.5 7.5"></path></svg>
                <calendar-month></calendar-month>
              </calendar-date>
            </div>
          </div>
          <div class="w-full">
            <%= form.label :comment, "コメント", class: "block text-lg font-semibold mb-1 w-full" %>
            <%= form.text_area :comment, placeholder: 'コメント', class: "textarea w-full h-30" %>
          </div>
        </section>
        <%= form.hidden_field :cover_image_url, value: book[:cover_image_url] %>
        <%= form.hidden_field :title, value: book[:title] %>
        <%= form.hidden_field :url, value: book[:url] %>
        <%= form.hidden_field :isbn, value: book[:isbn] %>
        <%= form.submit "リストに登録", class: "btn btn-primary", id: "submit-#{book[:isbn]}", disabled: true %>
      <% end %>
    <% end %>
  </div>
</section>

app/views/books/_search_books.html.erb
<section>
  <%= form_with url: new_list_book_path(@list), method: :get, local: true do |form| %>
    <div class="flex gap-5 justify-center items-center">
      <%= form.text_field :title, placeholder: "書籍タイトル", class: "input" %>
      <%= form.submit "検索", class: "btn btn-primary" %>
    </div>
    <p class="text-sm">※現在あいまい検索は対応していません</p>
  <% end %>
</section>

<% if @result.present? %>
  <h2 class="text-xl font-semibold text-center">検索結果</h2>
  <div class="grid grid-cols-1 gap-6 justify-center items-start w-full lg:grid-cols-3">
    <% if @result[:books].present? %>
      <% @result[:books].each do |book| %>
        <%= render 'book', book: book %>
      <% end %>
    <% else %>
      <div class="text-center">
        <p>該当する書籍はありませんでした。</p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/edit.html.erb
<script type="module" src="https://unpkg.com/cally"></script>
<article class="flex flex-col items-center justify-between gap-8">
  <h1 class="zen-maru-gothic-bold text-4xl text-center"><%= title "書籍編集" %></h1>

  <div class="bg-white p-4 flex flex-col items-center justify-between gap-4 w-full">
    <figure>
      <%= image_tag(@book.cover_image_url, alt: @book.title) %>
    </figure>
    <h2 class="text-xl font-bold link link-primary"><a href="<%= @book.url %>" target="_blankc" ><%= @book.title %></a></h2>
    <section>
      <% if @book.categories.present? %>
        <% @book.categories.map do |category| %>
          <span class="badge  badge-ghost"><%= category.name %></span>
        <% end %>
      <% else %>
        <span class="badge badge-ghost">未設定</span>
      <% end %>
    </section>
    <section class="w-full">
      <%= form_with model: @list_book, url: list_book_path(list_id: @list.id, id: @book.id), data: { turbo: true }, class: "text-start w-full flex flex-col items-start gap-4" do |f| %>
        <div>
          <h3 class="text-lg font-semibold">読了日<span class="text-red-600 align-top">*</span></h3>
          <button type="button" popovertarget="cally-popover1" class="input input-border" style="anchor-name:--cally1" id="cally1">
            <%= @list_book.read_completed_at %>
          </button>
          <%= f.hidden_field :read_completed_at, id: "read_completed_at" %>
          <div popover id="cally-popover1" class="dropdown bg-base-100 rounded-box shadow-lg" style="position-anchor:--cally1">
            <calendar-date class="cally" onChange="document.getElementById('cally1').innerText = this.value;document.getElementById('read_completed_at').value = this.value;" max="<%= Date.today %>" locale="ja-JP">
              <svg aria-label="Previous" class="fill-current size-4" slot="previous" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M15.75 19.5 8.25 12l7.5-7.5"></path></svg>
              <svg aria-label="Next" class="fill-current size-4" slot="next" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m8.25 4.5 7.5 7.5-7.5 7.5"></path></svg>
              <calendar-month></calendar-month>
            </calendar-date>
          </div>
        </div>
        <div class="w-full">
          <h3 class="text-lg font-semibold">コメント</h3>
          <%= f.text_area :comment, placeholder: 'コメント', class: "textarea w-full h-30" %>
        </div>
        <%= f.submit "更新", class: "btn btn-primary m-auto" %>
      <% end %>
    </section>
    <section class="flex items-center justify-center gap-3">
      <%= link_to '削除', list_book_path(@list.id, @book.isbn), data: { turbo_method: :delete }, class: "btn btn-error" %>
      <%= link_to '戻る', list_book_path(list_id: @list_book.list_id, id: @book.id), class: "btn" %>
    </section>
  </div>
</article>

app/views/books/new.html.erb
<script type="module" src="https://unpkg.com/cally"></script>
<article class="flex flex-col items-center justify-center gap-8">
  <h1 class="zen-maru-gothic-bold text-4xl text-center"><%= title "書籍登録" %></h1>
  <%= link_to "#{@list.name}の詳細ページ", list_path(@list), class: "link link-primary" %>
  <%= render "books/search_books" %>
</article>

app/views/books/show.html.erb
<article class="flex flex-col items-center justify-center gap-8 lg:max-w-2xl lg:mx-auto">
  <h1 class="zen-maru-gothic-bold text-4xl text-center"><%= title "書籍詳細" %></h1>
  <div class="bg-white p-4 flex flex-col items-center justify-between gap-4 w-full lg:py-6 lg:px-8">
    <figure>
      <%= image_tag(@book.cover_image_url, alt: @book.title) %>
    </figure>
    <h2 class="text-xl font-bold link link-primary"><a href="<%= @book.url %>" target="_blankc" ><%= @book.title %></a></h2>
    <section>
      <% if @book.categories.present? %>
        <% @book.categories.map do |category| %>
          <span class="badge  badge-ghost"><%= category.name %></span>
        <% end %>
      <% else %>
        <span class="badge badge-ghost">未設定</span>
      <% end %>
    </section>
    <section class="text-start w-full flex flex-col items-start gap-2">
      <div>
        <h3 class="text-lg font-semibold">読了日</h3>
        <p><%= @list_book.read_completed_at.strftime('%Y年%m月%d日') if @list_book.read_completed_at %></p>
      </div>
      <div>
        <h3 class="text-lg font-semibold">コメント</h3>
        <p class="whitespace-pre-wrap"><%= @list_book.comment %></p>
      </div>
    </section>
    <section class="flex justify-center gap-3">
      <% if current_user&.id == @list_book.list.user_id %>
        <%= link_to '編集', edit_list_book_path(@list_book.list_id, @book.id), class: "link" %>
      <% end %>
      <%= link_to 'リストに戻る', list_path(@list_book.list_id), class: "link" %>
    </section>
  </div>
</article>