config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "static_pages#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get "/login", to: "sessions#new", as: :login
  delete "/logout", to: "sessions#destroy", as: :logout
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'contact', to: 'static_pages#contact'

  resources :users, only: %i[index show edit update]
  resources :lists do
    resources :books, except: %i[index]
  end
end

app/views/layouts/_flash_messages.html.erb
<% if flash.any? %>
  <div class="container mx-auto px-4 py-4">
    <% flash.each do |message_type, message| %>
      <div class="alert shadow-lg mb-4 <%= message_type_class(message_type) %> alert-soft %> flex justify-between">
        <div class="flex items-center">
          <%= message_type_icon(message_type) %>
          <span><%= message %></span>
        </div>
        <button class="btn btn-sm btn-ghost" onclick="this.parentElement.remove()">✕</button>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="p-6 pb-3 bg-base-200 w-full flex flex-col gap-4 justify-center items-center">
  <div class="flex justify-between items-center w-full lg:max-w-[780px] mx-auto">
    <h2 class=""><%= image_tag "logo.png", alt: "Logo", class: "h-20 w-auto" %></h2>
    <div>
      <nav class="ml-auto">
        <ul class="flex flex-col gap-1 text-end lg:flex-row lg:gap-3">
          <li><%= link_to "Contact", contact_path, class: "link" %></li>
          <li><%= link_to "Privacy Policy", privacy_policy_path, class: "link" %></li>
          <li><%= link_to "Terms Of Service", terms_of_service_path, class: "link" %></li>
        </ul>
      </nav>
    </div>
  </div>
  <p class="w-full text-center">© <%= Date.today.year %> 来読-ReadMap-製作委員会</p>
</footer>

app/views/layouts/_header.html.erb
<div class="bg-base-300 shadow-lg">
  <div class="lg:w-[980px] mx-auto navbar" >
    <div class="navbar-start">
      <%= link_to root_path, class: "overflow-hidden w-20 h-auto" do %>
        <%= image_tag "logo.png", alt: "Logo", class: "w-full object object-contain" %>
      <% end %>
    </div>

    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal px-1">
        <li><%= link_to "ホーム", root_path, class: "btn btn-ghost" %></li>
        <% if logged_in? %>
          <li><%= link_to "ユーザー一覧", users_path, class: "btn btn-ghost" %></li>
        <% end %>
        <li><%= link_to "リスト一覧", lists_path, class: "btn btn-ghost" %></li>
      </ul>
    </div>

    <div class="navbar-end">
      <% if logged_in? %>
        <div class="flex items-center gap-2">
          <div class="dropdown dropdown-end">
            <label tabindex="0" class="btn btn-ghost btn-circle avatar">
              <div class="w-10 h-10 rounded-full bg-primary text-primary-content flex items-center justify-center leading-none">
                <span class="text-lg font-bold flex items-center justify-center h-full"><%= current_user.name.first.upcase %></span>
              </div>
            </label>
            <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
              <li class="menu-title">
                <span><%= current_user.name %></span>
              </li>
              <li><%= link_to "マイページ", user_path(current_user) %></li>
              <li><%= button_to "ログアウト", logout_path, method: :delete, class: "text-error" %></li>
            </ul>
          </div>
        <%= link_to 'マイページ', user_path(current_user), class: "hidden lg:btn lg:btn-primary lg:btn-sm" %>
        <%= button_to "ログアウト", logout_path, method: :delete, class: "hidden lg:btn lg:btn-error lg:btn-sm" %>
        </div>
      <% else %>
        <div class="flex items-center gap-2">
          <%= link_to login_path, class: "btn btn-primary btn-sm" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
            </svg>
            ログイン
          <% end %>
        </div>
      <% end %>
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
          </svg>
        </label>
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
          <li><%= link_to "ホーム", root_path %></li>
          <li><%= link_to "リスト一覧", lists_path %></li>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <% if logged_in? %>
            <li><%= link_to "マイページ", user_path(current_user) %></li>
            <li><%= button_to "ログアウト", logout_path, method: :delete, class: "text-error" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= display_meta_tags(default_meta_tags) %>
    <!-- Google tag (gtag.js) -->
    <% if Rails.env.production? %>
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-8VH2MH3EW9"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-8VH2MH3EW9');
      </script>
    <% end %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&family=Zen+Maru+Gothic:wght@400;500;700&display=swap" rel="stylesheet">
  </head>

  <body class="flex flex-col min-h-screen noto-sans-jp bg-yellow-950/20 ">
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages'%>
    <main class="flex-grow mx-auto w-[95%] my-8 max-w-7xl">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>